--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1
-- Dumped by pg_dump version 15.1

-- Started on 2024-01-31 13:50:07

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 3474 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 232 (class 1259 OID 16608)
-- Name: type_of_food_in_menu; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.type_of_food_in_menu (
    id integer NOT NULL,
    type character varying(20) NOT NULL
);


ALTER TABLE public.type_of_food_in_menu OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 16666)
-- Name: Type_of_food_in_menu_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.type_of_food_in_menu ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."Type_of_food_in_menu_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16574)
-- Name: account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account (
    email character varying(45) DEFAULT NULL::character varying,
    password character varying(45) DEFAULT NULL::character varying,
    id_site integer NOT NULL
);


ALTER TABLE public.account OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 16737)
-- Name: account_ID_Site_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account ALTER COLUMN id_site ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."account_ID_Site_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16579)
-- Name: check; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."check" (
    id_status integer NOT NULL,
    summa numeric(18,2) NOT NULL,
    data_check date NOT NULL,
    id_client integer NOT NULL,
    delivery_done integer DEFAULT 1 NOT NULL
);


ALTER TABLE public."check" OWNER TO postgres;

--
-- TOC entry 3475 (class 0 OID 0)
-- Dependencies: 225
-- Name: COLUMN "check".id_client; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."check".id_client IS 'client who made an order';


--
-- TOC entry 226 (class 1259 OID 16582)
-- Name: client; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.client (
    id_client integer NOT NULL,
    name character varying(50) NOT NULL,
    fhone character varying(50) NOT NULL,
    bonus character varying(50) NOT NULL
);


ALTER TABLE public.client OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16593)
-- Name: menu; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.menu (
    id_menu integer NOT NULL,
    name_menu character varying(50) NOT NULL,
    price numeric(18,2) NOT NULL,
    discount numeric(18,2) NOT NULL,
    type_of_food integer DEFAULT 1 NOT NULL
);


ALTER TABLE public.menu OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16598)
-- Name: order; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."order" (
    id_order integer NOT NULL,
    data_otp date NOT NULL,
    data_prib date NOT NULL,
    status integer DEFAULT 1 NOT NULL,
    id_menu integer DEFAULT 1 NOT NULL
);


--
-- Все селекты, оконные функции и Агрегатные функции
--

ALTER TABLE public."order" OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 16793)
-- Name: cointaner_of_order; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.cointaner_of_order AS
 SELECT string_agg((menu.name_menu)::text, '/'::text) AS "Состав_Заказа"
   FROM (public."order" ord
     JOIN public.menu ON ((menu.id_menu = ord.id_menu)))
  WHERE (ord.id_order = 1);


ALTER TABLE public.cointaner_of_order OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16587)
-- Name: couries; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.couries (
    phone_couries character varying(50) NOT NULL,
    "time" time with time zone,
    delivery_entity integer
);


ALTER TABLE public.couries OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 16619)
-- Name: tip_dostavki; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tip_dostavki (
    id integer NOT NULL,
    name_dostavki character varying(30) NOT NULL
);


ALTER TABLE public.tip_dostavki OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 16825)
-- Name: count_of_couries; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.count_of_couries AS
 SELECT ( SELECT tip_dostavki_1.name_dostavki
           FROM public.tip_dostavki tip_dostavki_1
          WHERE (tip_dostavki_1.id = 2)) AS "Название_доставки",
    count(couries.delivery_entity) AS "Колво_курьеров"
   FROM (public.tip_dostavki
     JOIN public.couries ON ((tip_dostavki.id = couries.delivery_entity)))
  WHERE (couries.delivery_entity = 2);


ALTER TABLE public.count_of_couries OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16590)
-- Name: delivery_list; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.delivery_list (
    data_prib date NOT NULL,
    payment_method character varying(50) NOT NULL,
    type_dostavka integer,
    order_id integer NOT NULL
);


ALTER TABLE public.delivery_list OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16603)
-- Name: status; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.status (
    id_status integer NOT NULL,
    name_status character varying(50) NOT NULL
);


ALTER TABLE public.status OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 16834)
-- Name: courier_in_a_way; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.courier_in_a_way AS
 SELECT couries.phone_couries AS "Номер_курьера",
    tip_dostavki.name_dostavki AS "Название_доставки",
    "check".data_check AS "Дата_Заказа",
    client.name AS "Имя_Клиента",
    status.name_status AS "Готовность_заказа"
   FROM ((((((public.couries
     JOIN public.tip_dostavki ON ((couries.delivery_entity = tip_dostavki.id)))
     JOIN public.delivery_list ON ((tip_dostavki.id = delivery_list.type_dostavka)))
     JOIN public."order" ON (("order".id_order = delivery_list.order_id)))
     JOIN public.status ON (("order".status = status.id_status)))
     JOIN public."check" ON ((delivery_list.order_id = "check".delivery_done)))
     JOIN public.client ON (("check".id_client = client.id_client)))
  WHERE (status.id_status = 2);


ALTER TABLE public.courier_in_a_way OWNER TO postgres;

--
-- TOC entry 250 (class 1259 OID 16848)
-- Name: get_price_over; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.get_price_over AS
 SELECT row_number() OVER () AS "Номер_чеков",
    "check".summa AS "Сумма_чека",
    sum("check".summa) OVER (ORDER BY "check".summa) AS "Приход_за_чек"
   FROM public."check";


ALTER TABLE public.get_price_over OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 16680)
-- Name: menu_id_menu_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.menu ALTER COLUMN id_menu ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menu_id_menu_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 16829)
-- Name: middle_cost_of_delivery; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.middle_cost_of_delivery AS
 SELECT ( SELECT tip_dostavki_1.name_dostavki
           FROM public.tip_dostavki tip_dostavki_1
          WHERE (tip_dostavki_1.id = 2)) AS "Наименование_компании",
    avg("check".summa) AS "Средняя_стоимость_чека_доставки"
   FROM (public."check"
     JOIN public.tip_dostavki ON (("check".delivery_done = tip_dostavki.id)))
  WHERE ("check".delivery_done = 2);


ALTER TABLE public.middle_cost_of_delivery OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 16811)
-- Name: middle_cost_of_shop; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.middle_cost_of_shop AS
 SELECT avg(menu.price) AS "Средняя_стоимость_всех_товаров"
   FROM public.menu;


ALTER TABLE public.middle_cost_of_shop OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 16839)
-- Name: pprice_with_discount; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.pprice_with_discount AS
 SELECT menu.name_menu AS "Наименование_продукта",
    menu.price AS "Цена",
    menu.discount AS "Скидка_в_проц",
    lead((menu.price * ((1)::numeric - (menu.discount / (100)::numeric))), 0, (0)::numeric) OVER (ORDER BY menu.id_menu) AS "Актуальная_цена_в_магазине"
   FROM public.menu;


ALTER TABLE public.pprice_with_discount OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 16789)
-- Name: price_of_order; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.price_of_order AS
 SELECT sum(menu.price) AS "Цена_Заказа"
   FROM (public."order" ord
     JOIN public.menu ON ((menu.id_menu = ord.id_menu)))
  WHERE (ord.id_order = 1);


ALTER TABLE public.price_of_order OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 16820)
-- Name: type_of_order; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.type_of_order AS
 SELECT "check".summa AS "Сумма_заказа",
    "check".data_check AS "Дата_Заказа",
    client.name AS "Имя_Клиента",
    tip_dostavki.name_dostavki AS "Название_доставки"
   FROM (((public."check"
     JOIN public.client ON ((client.id_client = "check".id_client)))
     JOIN public.delivery_list ON (("check".delivery_done = delivery_list.order_id)))
     JOIN public.tip_dostavki ON ((delivery_list.type_dostavka = tip_dostavki.id)));


ALTER TABLE public.type_of_order OWNER TO postgres;

--
-- TOC entry 252 (class 1259 OID 16856)
-- Name: rank_of_orders; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.rank_of_orders AS
 SELECT type_of_order."Сумма_заказа",
    type_of_order."Дата_Заказа",
    type_of_order."Имя_Клиента",
    type_of_order."Название_доставки",
    row_number() OVER (ORDER BY type_of_order."Сумма_заказа") AS "Топ_заказов"
   FROM public.type_of_order;


ALTER TABLE public.rank_of_orders OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 16852)
-- Name: rank_of_users; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.rank_of_users AS
 SELECT client.name AS "имя_клиента",
    client.bonus AS "Бонусы",
    row_number() OVER (ORDER BY client.bonus) AS "Топ_бонусов"
   FROM public.client;


ALTER TABLE public.rank_of_users OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 16843)
-- Name: ready_order_money; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.ready_order_money AS
 SELECT "check".data_check AS "Дата_Заказа",
    "check".summa AS "Сумма",
    delivery_list.payment_method AS "способ_оплаты",
    status.name_status AS "Готовность_заказа"
   FROM (((public."check"
     JOIN public.delivery_list ON (("check".delivery_done = delivery_list.order_id)))
     JOIN public."order" ON (("order".id_order = delivery_list.order_id)))
     JOIN public.status ON (("order".status = status.id_status)))
  WHERE (((delivery_list.payment_method)::text = 'наличная'::text) AND (status.id_status = 1));


ALTER TABLE public.ready_order_money OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 16800)
-- Name: tip_dostavki_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tip_dostavki ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."tip_dostavki_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 16676)
-- Name: vegetables; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vegetables AS
 SELECT menu.id_menu,
    menu.name_menu,
    menu.price,
    menu.discount,
    menu.type_of_food
   FROM public.menu
  WHERE (menu.type_of_food = 1);


ALTER TABLE public.vegetables OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 16815)
-- Name: who_made_payment_check_on_mail; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.who_made_payment_check_on_mail AS
 SELECT account.email AS "email_Клиента",
    delivery_list.payment_method AS "способ_оплаты"
   FROM ((public."check"
     JOIN public.account ON ((account.id_site = "check".id_client)))
     JOIN public.delivery_list ON (("check".delivery_done = delivery_list.order_id)))
  WHERE ((delivery_list.payment_method)::text = 'безналичная'::text);


ALTER TABLE public.who_made_payment_check_on_mail OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 16806)
-- Name: who_made_payment_online; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.who_made_payment_online AS
 SELECT client.name AS "Имя_Клиента",
    delivery_list.payment_method AS "способ_оплаты"
   FROM ((public."check"
     JOIN public.client ON ((client.id_client = "check".id_client)))
     JOIN public.delivery_list ON (("check".delivery_done = delivery_list.order_id)))
  WHERE ((delivery_list.payment_method)::text = 'безналичная'::text);


ALTER TABLE public.who_made_payment_online OWNER TO postgres;

--
-- TOC entry 3300 (class 2606 OID 16612)
-- Name: type_of_food_in_menu ID_Country; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.type_of_food_in_menu
    ADD CONSTRAINT "ID_Country" PRIMARY KEY (id);


--
-- TOC entry 3302 (class 2606 OID 16623)
-- Name: tip_dostavki ID_Dostavki; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tip_dostavki
    ADD CONSTRAINT "ID_Dostavki" PRIMARY KEY (id);


--
-- TOC entry 3290 (class 2606 OID 16743)
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id_site);


--
-- TOC entry 3292 (class 2606 OID 16586)
-- Name: client client_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT client_pkey PRIMARY KEY (id_client);


--
-- TOC entry 3294 (class 2606 OID 16763)
-- Name: delivery_list delivery_list_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delivery_list
    ADD CONSTRAINT delivery_list_pkey PRIMARY KEY (order_id);


--
-- TOC entry 3296 (class 2606 OID 16597)
-- Name: menu menu_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menu
    ADD CONSTRAINT menu_pkey PRIMARY KEY (id_menu);


--
-- TOC entry 3298 (class 2606 OID 16607)
-- Name: status status_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.status
    ADD CONSTRAINT status_pkey PRIMARY KEY (id_status);


--
-- TOC entry 3288 (class 1259 OID 16659)
-- Name: account_email_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_email_idx ON public.account USING btree (email text_pattern_ops);


--
-- TOC entry 3304 (class 2606 OID 16660)
-- Name: check Client_base; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."check"
    ADD CONSTRAINT "Client_base" FOREIGN KEY (id_client) REFERENCES public.client(id_client) NOT VALID;


--
-- TOC entry 3303 (class 2606 OID 16744)
-- Name: account Client_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT "Client_id" FOREIGN KEY (id_site) REFERENCES public.client(id_client) NOT VALID;


--
-- TOC entry 3309 (class 2606 OID 16751)
-- Name: order Menu_item; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT "Menu_item" FOREIGN KEY (id_menu) REFERENCES public.menu(id_menu) NOT VALID;


--
-- TOC entry 3305 (class 2606 OID 16771)
-- Name: check delivery_done; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."check"
    ADD CONSTRAINT delivery_done FOREIGN KEY (delivery_done) REFERENCES public.delivery_list(order_id) NOT VALID;


--
-- TOC entry 3306 (class 2606 OID 16710)
-- Name: couries id_entertaintment; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.couries
    ADD CONSTRAINT id_entertaintment FOREIGN KEY (delivery_entity) REFERENCES public.tip_dostavki(id) NOT VALID;


--
-- TOC entry 3310 (class 2606 OID 16764)
-- Name: order id_order; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT id_order FOREIGN KEY (id_order) REFERENCES public.delivery_list(order_id) NOT VALID;


--
-- TOC entry 3311 (class 2606 OID 16725)
-- Name: order status_order; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT status_order FOREIGN KEY (status) REFERENCES public.status(id_status) NOT VALID;


--
-- TOC entry 3307 (class 2606 OID 16715)
-- Name: delivery_list type_of_delivery; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delivery_list
    ADD CONSTRAINT type_of_delivery FOREIGN KEY (type_dostavka) REFERENCES public.tip_dostavki(id) NOT VALID;


--
-- TOC entry 3308 (class 2606 OID 16667)
-- Name: menu type_of_food; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menu
    ADD CONSTRAINT type_of_food FOREIGN KEY (type_of_food) REFERENCES public.type_of_food_in_menu(id) NOT VALID;


-- Completed on 2024-01-31 13:50:08

--
-- PostgreSQL database dump complete
--

